# Generated by Django 3.1 on 2020-08-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200812_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default='e232', max_length=200),
            preserve_default=False,
        ),
    ]
